# Generated by Django 5.0.1 on 2024-01-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.CharField(default=30, max_length=20),
            preserve_default=False,
        ),
    ]
